# -*- coding: utf-8 -*-
"""insertionsort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VNNKJOs5rAuDHAYWsO-byhM86d7PmnYy
"""

import time
import random
import pandas as pd

def Sort_insert(A):
    for i in range(1, len(A)):
        # Set key:
        key = A[i]

        j = i - 1
        while j >= 0 and A[j] > key:
            # Swap:
            A[j + 1] = A[j]
            A[j] = key
            # Decrement 'j':
            j -= 1

    return A

# a function that generates a list of 20, 100, 1000, and 4000 random integers between 
# 0 and 6000 integers.
data20 = random.sample(range(0,6000), 20)
data100 = random.sample(range(0,6000), 100)
data1000 = random.sample(range(0,6000), 1000)
data4000 = random.sample(range(0,6000), 4000)

df_20 = pd.DataFrame(data20)
df_100 = pd.DataFrame(data100)
df_1000 = pd.DataFrame(data1000)
df_4000 = pd.DataFrame(data4000)

# saving these in 4 files: arr20.txt, arr100.txt, arr1000.txt and arr4000.txt
df_20.to_csv('arr20.txt', index=False)
df_100.to_csv('arr100.txt', index=False)
df_1000.to_csv('arr1000.txt', index=False)
df_4000.to_csv('arr4000.txt', index=False)

# Reading the contents of the files
file20 = pd.read_csv('arr20.txt')
file100 = pd.read_csv('arr100.txt')
file1000 = pd.read_csv('arr1000.txt')
file4000 = pd.read_csv('arr4000.txt')

# Reading the contents into an array
Array20 = [i[0] for i in file20.values.tolist()]
Array100 = [i[0] for i in file100.values.tolist()]
Array1000 = [i[0] for i in file1000.values.tolist()]
Array4000 = [i[0] for i in file4000.values.tolist()]

print("-----------------------------------Insertion sort-----------------------------------")
print("Unsorted Array of Random 20 numbers: ", Array20)

begin = time.process_time()             # Starting the stopwatch
sorted_Array20 = Sort_insert(Array20)   # Passing the Array20 into insertion sort algorithm
end = time.process_time()               # Ending the stopwatch
print('\nDuration for insertion sorting array of 20 numbers : {}'.format(end - begin))  # Calculating Time on stopwatch
print('Sorted 20 Numbers: \t', sorted_Array20)

begin = time.process_time()
sorted_Array100 = Sort_insert(Array100)   # Passing the Array100 into insertion sort algorithm
end = time.process_time()
print('\nDuration for insertion sorting array of 100 numbers : {}'.format(end - begin))
print('Sorted 100 Numbers: \t', sorted_Array100)

begin = time.process_time()
sorted_Array1000 = Sort_insert(Array1000) # Passing the Array1000 into insertion sort algorithm
end = time.process_time()
print('\nDuration for insertion sorting array of 1000 numbers : {}'.format(end - begin))
print('Sorted 1000 Numbers: \t', sorted_Array1000)

begin = time.process_time()
sorted_Array4000 = Sort_insert(Array4000) # Passing the Array4000 into insertion sort algorithm
end = time.process_time()
print('\nDuration for insertion sorting array of 4000 numbers : {}'.format(end - begin))
print('Sorted 4000 Numbers: \t', sorted_Array4000)